Repository googleapis/google-auth-library-python, pull requests merged in 2019-11, with the labels that each got.

#380 chore: release v1.7.0
  CHANGELOG.md
  CHANGELOG.rst
  setup.py
Labels: autorelease: pending, cla: yes

#385 docs: fix note rendering for `service_account_email`
  google/auth/compute_engine/credentials.py
Labels: cla: yes, type: docs

#381 chore: remove unused badges, update author_email
  README.rst
  setup.py
Labels: cla: yes

#387 fix: fix check for 'internal_failure' condition
  google/oauth2/_client.py
  tests/oauth2/test__client.py
Labels: cla: yes

#378 build: enable release-please
  .github/release-please.yml
Labels: cla: yes

#390 fix: make gRPC auth plugin non-blocking + add default timeout value f…
  google/auth/transport/grpc.py
  google/auth/transport/requests.py
  tests/transport/test_grpc.py
Labels: cla: yes
