Repository googleapis/google-auth-library-python, pull requests merged in 2020-07, with the labels that each got.

#515 chore: update file headers
  .kokoro/publish-docs.sh
  .kokoro/release.sh
  .kokoro/trampoline.sh
  synth.metadata
  synth.py
Labels: automerge, cla: yes, context: none

#546 feat: add quota project to base credentials class
  .gitignore
  google/auth/_default.py
  google/auth/app_engine.py
  google/auth/compute_engine/credentials.py
  google/auth/credentials.py
  google/auth/impersonated_credentials.py
  google/auth/jwt.py
  google/oauth2/credentials.py
  google/oauth2/service_account.py
  tests/compute_engine/test_credentials.py
  tests/oauth2/test_credentials.py
  tests/oauth2/test_service_account.py
  tests/test__default.py
  tests/test_app_engine.py
  tests/test_credentials.py
  tests/test_iam.py
  tests/test_impersonated_credentials.py
  tests/test_jwt.py
  tests/transport/test_grpc.py
  tests/transport/test_requests.py
  tests/transport/test_urllib3.py
Labels: automerge, cla: yes

#560 fix: don't add empty quota project
  google/auth/_default.py
  tests/test__default.py
Labels: cla: yes

#563 Revert "fix: migrate signBlob to iamcredentials.googleapis.com"
  .gitignore
  google/auth/iam.py
  system_tests/test_service_account.py
  tests/compute_engine/test_credentials.py
  tests/test_iam.py
Labels: automerge, cla: yes

#564 docs: add 3.8 support to contributing
  CONTRIBUTING.rst
Labels: cla: yes

#473 feat: Add debug logging that can help with diagnosing auth lib. path
  google/auth/_default.py
Labels: automerge, cla: yes

#527 test: add more tests for service account quota projects
  tests/oauth2/test_credentials.py
  tests/oauth2/test_service_account.py
Labels: automerge, cla: yes

#474 feat: Show the transport exception that happened for GCE Metadata
  google/auth/compute_engine/_metadata.py
Labels: automerge, cla: yes

#556 chore: update kokoro config (via synth)
  .kokoro/build.sh
  .kokoro/continuous/common.cfg
  .kokoro/presubmit/common.cfg
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/lint/continuous.cfg
  .kokoro/samples/lint/periodic.cfg
  .kokoro/samples/lint/presubmit.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.6/continuous.cfg
  .kokoro/samples/python3.6/periodic.cfg
  .kokoro/samples/python3.6/presubmit.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.7/continuous.cfg
  .kokoro/samples/python3.7/periodic.cfg
  .kokoro/samples/python3.7/presubmit.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.8/continuous.cfg
  .kokoro/samples/python3.8/periodic.cfg
  .kokoro/samples/python3.8/presubmit.cfg
  .kokoro/test-samples.sh
  synth.metadata
Labels: automerge, cla: yes, context: partial

#569 feat(packaging): add support for Python 3.8
  docs/reference/google.auth.compute_engine.rst
  docs/reference/google.auth.crypt.rst
  docs/reference/google.auth.rst
  docs/reference/google.auth.transport.rst
  docs/reference/google.oauth2.rst
  docs/reference/google.rst
  noxfile.py
  setup.py
Labels: automerge, cla: yes

#572 feat: asyncio http request logic and asynchronous credentials logic
  google/auth/credentials_async.py
  google/auth/transport/aiohttp_requests.py
  noxfile.py
  tests_async/test_credentials.py
  tests_async/transport/__init__.py
  tests_async/transport/async_compliance.py
  tests_async/transport/test_aiohttp_requests.py
Labels: cla: yes

#439 fix: set Content-Type header in the request to signBlob API to avoid Invalid JSON payload error
  google/auth/iam.py
  tests/test_iam.py
Labels: automerge, cla: yes

#573 feat: all asynchronous credential types required for all authentication types (service accounts, default... etc)
  docs/reference/google.auth.credentials_async.rst
  docs/reference/google.auth.jwt_async.rst
  docs/reference/google.auth.rst
  docs/reference/google.auth.transport.aiohttp_requests.rst
  docs/reference/google.auth.transport.mtls.rst
  docs/reference/google.auth.transport.rst
  docs/reference/google.oauth2.credentials_async.rst
  docs/reference/google.oauth2.rst
  docs/reference/google.oauth2.service_account_async.rst
  google/auth/__init__.py
  google/auth/_default_async.py
  google/auth/credentials_async.py
  google/auth/jwt_async.py
  google/oauth2/_client_async.py
  google/oauth2/credentials_async.py
  google/oauth2/service_account_async.py
  tests_async/__init__.py
  tests_async/conftest.py
  tests_async/oauth2/test__client_async.py
  tests_async/oauth2/test_credentials_async.py
  tests_async/oauth2/test_service_account_async.py
  tests_async/test__default_async.py
  tests_async/test_credentials_async.py
  tests_async/test_jwt_async.py
  tests_async/transport/async_compliance.py
Labels: cla: yes

#574 feat: added system tests for the asyncIO auth changes and async id_token credentials
  google/oauth2/id_token_async.py
  system_tests/noxfile.py
  system_tests/system_tests_async/conftest.py
  system_tests/system_tests_async/test_default.py
  system_tests/system_tests_async/test_id_token.py
  system_tests/system_tests_async/test_service_account.py
  system_tests/system_tests_sync/.gitignore
  system_tests/system_tests_sync/__init__.py
  system_tests/system_tests_sync/app_engine_test_app/.gitignore
  system_tests/system_tests_sync/app_engine_test_app/app.yaml
  system_tests/system_tests_sync/app_engine_test_app/appengine_config.py
  system_tests/system_tests_sync/app_engine_test_app/main.py
  system_tests/system_tests_sync/app_engine_test_app/requirements.txt
  system_tests/system_tests_sync/conftest.py
  system_tests/system_tests_sync/secrets.tar.enc
  system_tests/system_tests_sync/test_app_engine.py
  system_tests/system_tests_sync/test_compute_engine.py
  system_tests/system_tests_sync/test_default.py
  system_tests/system_tests_sync/test_grpc.py
  system_tests/system_tests_sync/test_id_token.py
  system_tests/system_tests_sync/test_impersonated_credentials.py
  system_tests/system_tests_sync/test_mtls_http.py
  system_tests/system_tests_sync/test_oauth2_credentials.py
  system_tests/system_tests_sync/test_service_account.py
  tests_async/oauth2/test_id_token.py
Labels: cla: yes
