Repository googleapis/google-auth-library-python, pull requests merged in 2020-09, with the labels that each got.

#561 refactor: split 'with_quota_project' into separate base class
  google/auth/app_engine.py
  google/auth/compute_engine/credentials.py
  google/auth/credentials.py
  google/auth/impersonated_credentials.py
  google/auth/jwt.py
  google/oauth2/credentials.py
  google/oauth2/service_account.py
  tests/test__default.py
  tests/test_credentials.py
Labels: cla: yes

#594 feat: defines internal utils for OAuth client Auth and error handling
  google/auth/exceptions.py
  google/oauth2/utils.py
  setup.py
  tests/oauth2/test_utils.py
Labels: cla: yes

#597 fix: trigger an auto release
  google/auth/credentials.py
Labels: cla: yes

#600 fix: "Revert "fix: migrate signBlob to iamcredentials.googleapis.com""
  .gitignore
  google/auth/iam.py
  system_tests/test_service_account.py
  tests/compute_engine/test_credentials.py
  tests/test_iam.py
Labels: cla: yes

#598 feat: implements the OAuth token exchange spec based on rfc8693
  .DS_Store
  google/auth/app_engine.py
  google/auth/compute_engine/credentials.py
  google/auth/credentials.py
  google/auth/impersonated_credentials.py
  google/auth/jwt.py
  google/oauth2/credentials.py
  google/oauth2/service_account.py
  google/oauth2/sts.py
  tests/oauth2/test_sts.py
  tests/test__default.py
  tests/test_credentials.py
Labels: cla: yes

#603 feat: defines `google.auth.external_account.Credentials` abstract class for external_account credentials
  .gitignore
  CHANGELOG.md
  google/auth/credentials.py
  google/auth/external_account.py
  google/auth/iam.py
  setup.py
  system_tests/test_service_account.py
  tests/compute_engine/test_credentials.py
  tests/test_external_account.py
  tests/test_iam.py
Labels: cla: yes

#602 fix(dependencies): aiohttp >= 3.6.2
  noxfile.py
  setup.py
Labels: cla: yes

#589 fix: fix expiry for `to_json()`
  google/oauth2/credentials.py
  tests/oauth2/test_credentials.py
Labels: automerge, cla: yes

#605 feat: adds service account impersonation to `google.auth.external_account.Credentials`
  .DS_Store
  google/auth/external_account.py
  google/auth/impersonated_credentials.py
  tests/test_external_account.py
  tests/test_impersonated_credentials.py
Labels: cla: yes

#609 chore: add default CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#610 docs: timeout docs updated to reflect aiohttp timeouts
  google/auth/transport/aiohttp_requests.py
Labels: cla: yes

#611 fix: move async to internal surface until stabilized
  docs/reference/google.auth.transport.aiohttp_requests.rst
  docs/reference/google.auth.transport.rst
  google/auth/_jwt_async.py
  google/auth/transport/_aiohttp_requests.py
  system_tests/system_tests_async/conftest.py
  tests_async/oauth2/test__client_async.py
  tests_async/test_jwt_async.py
  tests_async/transport/test_aiohttp_requests.py
Labels: cla: yes, kokoro:run
