Repository googleapis/google-auth-library-python, pull requests merged in 2020-10, with the labels that each got.

#617 feat: defines `google.auth.identity_pool.Credentials` used for K8s and Azure workloads
  google/auth/identity_pool.py
  tests/data/external_subject_token.json
  tests/data/external_subject_token.txt
  tests/test_identity_pool.py
Labels: cla: yes

#619 fix: move aiohttp to extra as it is currently internal surface
  setup.py
Labels: automerge, cla: yes

#596 fix: remove checks for ancient versions of Cryptography
  google/auth/crypt/_cryptography_rsa.py
  google/auth/crypt/es256.py
Labels: automerge, cla: yes

#622 feat: implements AWS signature version 4 for signing requests
  google/auth/aws.py
  tests/test_aws.py
Labels: cla: yes

#625 feat: defines `google.auth.aws.Credentials` used for AWS workloads
  CHANGELOG.md
  google/auth/aws.py
  google/auth/crypt/_cryptography_rsa.py
  google/auth/crypt/es256.py
  google/auth/environment_vars.py
  setup.py
  tests/test_aws.py
Labels: cla: yes

#630 tests: fix unit tests on python 3.6 / 3.7
  noxfile.py
Labels: cla: yes

#628 chore: sync to master
  noxfile.py
  setup.py
  tests/test_identity_pool.py
Labels: cla: yes

#588 Change metadata service helper to work with any query parameters
  google/auth/compute_engine/_metadata.py
  google/auth/compute_engine/credentials.py
  tests/compute_engine/test__metadata.py
Labels: automerge, cla: yes

#634 fix: pin 'aoihttp < 3.7.0dev'
  noxfile.py
  setup.py
  system_tests/noxfile.py
Labels: automerge, cla: yes

#631 feat: implement `get_project_id()` for google.auth.external_account.Credentials
  google/auth/compute_engine/_metadata.py
  google/auth/compute_engine/credentials.py
  google/auth/external_account.py
  noxfile.py
  tests/compute_engine/test__metadata.py
  tests/test_external_account.py
Labels: cla: yes

#578 chore: add infrastructure to support `docs-presubmit` build (via synth)
  .kokoro/docker/docs/Dockerfile
  .kokoro/docker/docs/fetch_gpg_keys.sh
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  .kokoro/publish-docs.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: cla: yes, context: full

#624 Update example in oauth2.id_token docs
  google/oauth2/id_token.py
Labels: automerge, cla: yes

#639 build: use pypi secret from secret manager
  .kokoro/build.sh
  .kokoro/docs/common.cfg
  .kokoro/populate-secrets.sh
  .kokoro/release/common.cfg
  .kokoro/samples/python3.6/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/test-samples.sh
  .kokoro/trampoline.sh
  synth.metadata
Labels: cla: yes, context: full

#633 feat: add custom scopes for access tokens from the metadata service
  google/auth/_default.py
  google/auth/_default_async.py
  google/auth/compute_engine/_metadata.py
  google/auth/compute_engine/credentials.py
  system_tests/noxfile.py
  tests/compute_engine/test_credentials.py
Labels: automerge, cla: yes

#640 fix(deps): Revert "fix: pin 'aoihttp < 3.7.0dev' (#634)" (#632)
  noxfile.py
  setup.py
  system_tests/noxfile.py
Labels: automerge, cla: yes

#635 feat: Support external_accounts in `google.auth.default()` & `google.auth.load_credentials_from_file()`
  google/auth/_default.py
  google/auth/aws.py
  google/auth/identity_pool.py
  noxfile.py
  setup.py
  system_tests/noxfile.py
  tests/test__default.py
  tests/test_aws.py
  tests/test_identity_pool.py
Labels: cla: yes
