Repository googleapis/google-auth-library-python, pull requests merged in 2021-07, with the labels that each got.

#796 chore: update authorized_user.json
  system_tests/secrets.tar.enc
Labels: cla: yes

#794 docs: fix code block formatting in 'user-guide.rst'
  docs/user-guide.rst
Labels: cla: yes

#793 feat: define `CredentialAccessBoundary` classes
  google/auth/downscoped.py
  tests/test_downscoped.py
Labels: cla: yes

#788 tests: pass '*session.posargs' for systests
  system_tests/noxfile.py
Labels: cla: yes

#801 feat: define `google.auth.downscoped.Credentials` class
  google/auth/downscoped.py
  tests/test_downscoped.py
Labels: cla: yes

#784 feat: service account is able to use a private token endpoint
  google/oauth2/service_account.py
  tests/oauth2/test_service_account.py
  tests_async/oauth2/test_service_account_async.py
Labels: automerge, cla: yes, kokoro:run

#748 fix: fix fetch_id_token credential lookup order to match adc
  google/oauth2/_id_token_async.py
  google/oauth2/id_token.py
  tests/oauth2/test_id_token.py
  tests_async/oauth2/test_id_token.py
Labels: cla: yes

#806 chore: update user credential secret
  system_tests/secrets.tar.enc
Labels: cla: yes

#805 fix: fallback to source creds expiration in downscoped tokens
  google/auth/downscoped.py
  tests/test_downscoped.py
Labels: cla: yes

#808 revert: "feat: service account is able to use a private token endpoint (#784)"
  google/oauth2/service_account.py
  tests/oauth2/test_service_account.py
  tests_async/oauth2/test_service_account_async.py
Labels: cla: yes

#813 chore: add Sijun and Silvano as CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#812 feat: support refresh callable on google.oauth2.credentials.Credentials
  google/oauth2/credentials.py
  tests/oauth2/test_credentials.py
Labels: cla: yes

#807 fix: do not use the GAE APIs on gen2+ runtimes
  google/auth/_default.py
  google/auth/environment_vars.py
  tests/test__default.py
  tests/test_app_engine.py
  tests_async/test__default_async.py
Labels: automerge, cla: yes

#820 chore: update authorized_user.json
  system_tests/secrets.tar.enc
Labels: automerge, cla: yes
