Repository googleapis/google-auth-library-python, pull requests merged in 2021-08, with the labels that each got.

#821 fix: Fix missing space in error message.
  google/auth/compute_engine/_metadata.py
Labels: automerge, cla: yes

#828 chore: update user secret file
  system_tests/secrets.tar.enc
Labels: cla: yes, automerge

#827 docs: update user guide/references for downscoped creds
  docs/index.rst
  docs/reference/google.auth.downscoped.rst
  docs/reference/google.auth.rst
  docs/user-guide.rst
Labels: cla: yes

#830 fix: downscoping documentation bugs
  docs/user-guide.rst
Labels: cla: yes

#834 chore: update secrets
  system_tests/secrets.tar.enc
Labels: cla: yes, automerge

#831 chore: omit 'docfx' from docs-presubmit build
  .kokoro/docker/docs/Dockerfile
  .kokoro/docs/common.cfg
  .kokoro/docs/docs-presubmit.cfg
  noxfile.py
  owlbot.py
Labels: cla: yes

#837 test: Add integration tests for downscoping
  CONTRIBUTING.rst
  system_tests/noxfile.py
  system_tests/system_tests_sync/test_downscoping.py
Labels: cla: yes

#835 feat: service account is able to use a private token endpoint
  google/oauth2/service_account.py
  tests/oauth2/test_service_account.py
  tests_async/oauth2/test_service_account_async.py
Labels: cla: yes

#838 test: address comments for downscoping tests
  system_tests/system_tests_sync/test_downscoping.py
Labels: cla: yes, automerge

#839 chore: release v1.35.0
  CHANGELOG.md
  google/auth/version.py
  system_tests/secrets.tar.enc
Labels: cla: yes

#840 chore: set release version to 2.0.0
  google/auth/version.py
Labels: cla: yes

#842 fix: aws path normalization in windows
  google/auth/aws.py
Labels: cla: yes

#846 fix: use int.from_bytes
  google/auth/crypt/es256.py
  system_tests/secrets.tar.enc
Labels: cla: yes

#848 fix: use 'int.to_bytes' rather than deprecated crypto wrapper
  google/auth/crypt/es256.py
Labels: kokoro:force-run, cla: yes

#849 chore: migrate default branch from master to main
  .kokoro/test-samples-impl.sh
  README.rst
  docs/conf.py
  docs/index.rst
  owlbot.py
Labels: cla: yes
