Repository googleapis/google-auth-library-python, pull requests merged in 2022-08, with the labels that each got.

#1094 chore: update system creds
  system_tests/secrets.tar.enc
Labels: automerge

#1091 fix: make expiration_time optional in response schema
  docs/user-guide.rst
  google/auth/pluggable.py
  tests/test_pluggable.py
Labels: kokoro:force-run

#1098 chore: Refresh system test creds
  system_tests/secrets.tar.enc
Labels: automerge

#1102 docs(samples): add auth samples and tests
  .github/sync-repo-settings.yaml
  .kokoro/samples-test-setup.sh
  .kokoro/samples/lint/common.cfg
  .kokoro/samples/python3.10/common.cfg
  .kokoro/samples/python3.7/common.cfg
  .kokoro/samples/python3.8/common.cfg
  .kokoro/samples/python3.9/common.cfg
  samples/cloud-client/snippets/authenticate_explicit_with_adc.py
  samples/cloud-client/snippets/authenticate_implicit_with_adc.py
  samples/cloud-client/snippets/idtoken_from_impersonated_credentials.py
  samples/cloud-client/snippets/idtoken_from_metadata_server.py
  samples/cloud-client/snippets/idtoken_from_service_account.py
  samples/cloud-client/snippets/noxfile.py
  samples/cloud-client/snippets/noxfile_config.py
  samples/cloud-client/snippets/requirements.txt
  samples/cloud-client/snippets/snippets_test.py
  samples/cloud-client/snippets/verify_google_idtoken.py
  system_tests/secrets.tar.enc
Labels: samples, owlbot:ignore
